### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by Emqo** [Aimerny/MCDRPlugins#83]
#### 您使用的版本？ | Your usage version?
KookIn 1.1.2
#### 您使用的场景？ | Your usage scenarios?
正常使用场景
#### 您做了什么操作？ | What did you do?
mc客户端里发送信息
#### 您遇到了什么问题？ | What are your problems?
控制台报错
#### 您期望的结果是怎样的？ | What is your expected outcome?
正常

#### (附加)必要的截图或日志 | (Additional) The capture or logs of this problem?

[MCDR] [23:42:21] [TaskExecutor/ERROR]: Error invoking listener EventListener(plugin='kookin@1.1.2', callback=<function on_user_info at 0x0000013F03F720C0>, priorit
y=1000)
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 773, in __trigger_listener_sync
    listener.callback(listener.plugin.server_interface, *args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\Kookin-v1.1.2.mcdr\kookin\__init__.py", line 61, in on_user_info
    PluginContext.get().kook_api.send_to_sync_channel(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        f"<{info.player}>{info.content}"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "plugins\Kookin-v1.1.2.mcdr\kookin\api\kook_api.py", line 127, in send_to_sync_channel
    self.send_text_to_channel(content, channel_info["channel_id"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\Kookin-v1.1.2.mcdr\kookin\api\kook_api.py", line 119, in send_text_to_channel
    asyncio.run_coroutine_threadsafe(send_to_channel(), self.__event_loop)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 1003, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 873, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 551, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Aimerny** [comment]
只看这个没办法确认到底是什么原因导致的，也没有足够的复现条件。请修改issue内容
1. 发送了什么消息
2. 配置内容
3. 完整的复现路径

**Comment by Emqo** [comment]
{
    "token": "1/MjE0ODQ=/erKHGPj86WOboacTRGNdBw==",
    "prefixes": [
        "/"
    ],
    "admin_channel": [
        {
            "channel_name": "机器人管理频道",
            "channel_id": "7870666809807011"
        }
    ],
    "public_channel": [
        {
            "channel_name": "服务器成员公共频道",
            "channel_id": "2201883894798903"
        }
    ],
    "sync_chat_channel": [
        {
            "channel_name": "服务器聊天同步频道",
            "channel_id": "2201883894798903"
        }
    ],
    "admins": [
        "Yoghurt#3953"
    ],
    "server_name": "Bugelll"
}

**Comment by Aimerny** [comment]
> Reference

没有什么有效信息，token信息请注意保密，请看第一条回复，需要提供完整的可复现路径。
观察报错猜测是某些原因导致eventloop停止，考虑使用`!!MCDR plg reload kookin`尝试重启插件。

**Comment by Aimerny** [comment]
如没有更多信息，我将会关闭此issue

> { "token": "_**", "prefixes": [ "/" ], "admin_channel": [ { "channel_name": "机器人管理频道", "channel_id": "**" } ], "public_channel": [ { "channel_name": "服务器成员公共频道", "channel_id": "__" } ], "sync_chat_channel": [ { "channel_name": "服务器聊天同步频道", "channel_id": "_*" } ], "admins": [ "Yoghurt#3953" ], "server_name": "Bugelll" }
